<?php

use App\Model\Answers\Model;

/** @var string[] $question  */

$answers = new Model();
?>
<html lang="en_US">

<head>
    <title>Quiz</title>
</head>
<body>
<div>
<form method="POST" action="/questionSubmit">
    <h1><?= $question['question_title'] ?></h1>
    <br />
    <br />

    <?php foreach ($answers->getAnswers() as $answer) : ?>
        <label>
            <input type="radio" name="answer_id" value="<?= $answer['id'] ?>">
            <pre><p><?= $answer['answer_text'] ?></p></pre>
        </label>
        <br />
    <?php endforeach; ?>

    <input type="hidden" name="question_id" value="<?= $_GET['question_id'] ?>" />
    <br /><br />
    <input type="submit" value="Submit" />
</form>
</div>
</body>
</html>