<style>
    .element {
        display: block;
        width: 30px;
        height: 20px;
        border: 1px solid black;
        padding: 3px;
        margin: 3px;
        text-align: center;
        float: left;
    }

    .current-question {
        font-weight: bold;
        background-color: coral;
        border-width: 3px;
    }

    .correct-answer {
        background-color: green;
    }

    .incorrect-answer {
        background-color: red;
    }
</style>
<?php

use App\Model\Question\Model;

$questions = new Model();
?>

<?php for ($i = 1; $i <= $questions->getTotal(); $i++) : ?>
    <a class="element
        <?php if ($i == $_GET['question_id']) : ?>current-question<?php endif; ?>
        <?php if (isset($_SESSION['answers'][$i])) : ?>
            <?php if ($_SESSION['answers'][$i]) : ?>
                correct-answer
            <?php else : ?>
                incorrect-answer
            <?php endif; ?>
        <?php endif; ?>
    " href="/question?question_id=<?= $i ?>">
        <?= $i ?>
    </a>
<?php endfor; ?>
<div style="clear: both;"></div>